[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname]($style) '
style = 'bold blue'
ssh_symbol = '🌐 '

[username]
show_always = false
format = '[$user]($style) in '
style_user = 'bold green'

[aws]
disabled = true

[package]
disabled = true

[python]

[nodejs]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)](bold 208) '
symbol = '🌱 '

[git_status]
disabled = true
